// src/app/components/image/image.component.ts
import { Component, Input } from "@angular/core";
import config from '../../../../config.json';

@Component({
  selector: "app-image",
  templateUrl: "./image.component.html"
})
export class Image {

  @Input() public name!: string;
  @Input() public alt!: string;
  @Input() public width?: number;
  @Input() public height?: number;

  private get base(): string {
    return (config as any).imagesBaseUrl ?? '';
  }

  public get srcSet(): string {
    return `${this.base}/${this.name}_1280.webp 1280w, ${this.base}/${this.name}_2880.webp 2880w`;
  }

  public get src(): string {
    return `${this.base}/${this.name}_1280.jpg`;
  }

}

<picture>
  <source
    [attr.srcset]="srcSet"
  />
  <img
    [src]="src"
    [attr.alt]="alt"
    [attr.width]="width"
    [attr.height]="height"
  />
</picture>

// src/components/images/Image.tsx
import config from '../../config.json';

interface ImageProps {
    name: string;
    alt: string;
    className?: string;
    width?: number;
    height?: number;
}

export const Image = ({
    name,
    alt,
    className = '', 
    width, 
    height  
}: ImageProps) => {
    const base: string = config.imagesBaseUrl;

    return (
        <picture>
            <source 
                srcSet={`${base}/${name}_1280.webp 1280w, ${base}/${name}_2880.webp 2880w`} 
                type="image/webp" 
            />
            <img 
                src={`${base}/${name}_1280.jpg`} 
                alt={alt}
                width={width}
                height={height}
                className={`block max-w-full h-auto ${className}`} 
            />
        </picture>
    );
};
