// src/components/images/Thumbnail.tsx
import config from '../../config.json';

interface ThumbnailProps {
    name: string;
    alt: string;
    className?: string;
    width?: number;
    height?: number;
}

export const Thumbnail = ({
    name,
    alt,
    className = '', 
    width = 640, 
    height  
}: ThumbnailProps) => {
    const base: string = config.imagesBaseUrl;

    return (
        <picture>
            <source srcSet={`${base}/${name}_640.webp`} type="image/webp" />
            <img 
                src={`${base}/${name}_640.jpg`} 
                alt={alt}
                width={width}
                height={height}
                loading="lazy"
                className={`block max-w-full h-auto ${className}`} 
            />
        </picture>
    );
};

// src/app/components/thumbnail/thumbnail.component.ts
import { Component, Input } from "@angular/core";
import config from '../../../../config.json';

@Component({
  selector: "app-thumbnail",
  templateUrl: "./thumbnail.component.html"
})
export class Thumbnail {

  @Input() public name!: string;
  @Input() public alt!: string;
  @Input() public width: number = 640;
  @Input() public height?: number;

  private get base(): string {
    return (config as any).imagesBaseUrl ?? '';
  }

  public get srcSet(): string {
    return `${this.base}/${this.name}_640.webp`;
  }

  public get src(): string {
    return `${this.base}/${this.name}_640.jpg`;
  }

}

<picture>
  <source [attr.srcset]="srcSet" type="image/webp" />
  <img
    [src]="src"
    [attr.alt]="alt"
    [attr.width]="width"
    [attr.height]="height"
    loading="lazy"
  />
</picture>
